<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="27" result="Failed" total="26" passed="10" failed="8" inconclusive="4" skipped="4" asserts="10" engine-version="3.9.0.0" clr-version="4.0.30319.42000" start-time="2018-10-30 01:06:27Z" end-time="2018-10-30 01:06:29Z" duration="1.810832">
  <command-line><![CDATA["C:\Users\codit\Downloads\nunit.console\nunit3-console.exe" .\test\assets\NUnit.Xml.TestLogger.NetFull.Tests\bin\Debug\net46\NUnit.Xml.TestLogger.NetFull.Tests.dll]]></command-line>
  <test-suite type="Assembly" id="0-1041" name="NUnit.Xml.TestLogger.NetFull.Tests.dll" fullname="C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetFull.Tests\bin\Debug\net46\NUnit.Xml.TestLogger.NetFull.Tests.dll" runstate="Runnable" testcasecount="27" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:29Z" duration="0.986133" total="26" passed="10" failed="8" warnings="1" inconclusive="4" skipped="4" asserts="10">
    <environment framework-version="3.8.1.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.17134.0" platform="Win32NT" cwd="C:\Users\codit\src\nunit.testlogger" machine-name="DESKTOP-0QEQ4G1" user="codit" user-domain="DESKTOP-0QEQ4G1" culture="en-US" uiculture="en-US" os-architecture="x86" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="C:\Users\codit\src\nunit.testlogger" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.6" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="448" />
      <property name="_APPDOMAIN" value="domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1042" name="NUnit" fullname="NUnit" runstate="Runnable" testcasecount="27" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:29Z" duration="0.968269" total="26" passed="10" failed="8" warnings="1" inconclusive="4" skipped="4" asserts="10">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="0-1043" name="Xml" fullname="NUnit.Xml" runstate="Runnable" testcasecount="27" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:29Z" duration="0.967602" total="26" passed="10" failed="8" warnings="1" inconclusive="4" skipped="4" asserts="10">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestSuite" id="0-1044" name="TestLogger" fullname="NUnit.Xml.TestLogger" runstate="Runnable" testcasecount="27" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:29Z" duration="0.967588" total="26" passed="10" failed="8" warnings="1" inconclusive="4" skipped="4" asserts="10">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-suite type="TestSuite" id="0-1045" name="NetFull" fullname="NUnit.Xml.TestLogger.NetFull" runstate="Runnable" testcasecount="27" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:29Z" duration="0.967578" total="26" passed="10" failed="8" warnings="1" inconclusive="4" skipped="4" asserts="10">
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-suite type="TestSuite" id="0-1047" name="Tests" fullname="NUnit.Xml.TestLogger.NetFull.Tests" runstate="Runnable" testcasecount="23" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.547275" total="22" passed="9" failed="7" warnings="1" inconclusive="3" skipped="3" asserts="9">
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-suite type="TestFixture" id="0-1022" name="FailingOneTimeSetUp" fullname="NUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeSetUp" classname="NUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeSetUp" runstate="Runnable" testcasecount="1" result="Failed" label="Error" site="SetUp" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.029992" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="0">
                <failure>
                  <message><![CDATA[System.InvalidOperationException : Operation is not valid due to the current state of the object.]]></message>
                  <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeSetUp.OneTimeSetUp() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 107]]></stack-trace>
                </failure>
                <test-case id="0-1023" name="Test" fullname="NUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeSetUp.Test" methodname="Test" classname="NUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeSetUp" runstate="Runnable" seed="640820598" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
                  <failure>
                    <message><![CDATA[OneTimeSetUp: System.InvalidOperationException : Operation is not valid due to the current state of the object.]]></message>
                  </failure>
                </test-case>
              </test-suite>
              <test-suite type="TestFixture" id="0-1028" name="FailingOneTimeTearDown" fullname="NUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeTearDown" classname="NUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeTearDown" runstate="Runnable" testcasecount="1" result="Failed" label="Error" site="TearDown" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.009047" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
                <failure>
                  <message><![CDATA[TearDown : System.InvalidOperationException : Operation is not valid due to the current state of the object.]]></message>
                  <stack-trace><![CDATA[--TearDown
   at NUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeTearDown.OneTimeTearDown() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 152]]></stack-trace>
                </failure>
                <test-case id="0-1029" name="Test" fullname="NUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeTearDown.Test" methodname="Test" classname="NUnit.Xml.TestLogger.NetFull.Tests.FailingOneTimeTearDown" runstate="Runnable" seed="706270237" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.005324" asserts="0" />
              </test-suite>
              <test-suite type="TestFixture" id="0-1026" name="FailingTearDown" fullname="NUnit.Xml.TestLogger.NetFull.Tests.FailingTearDown" classname="NUnit.Xml.TestLogger.NetFull.Tests.FailingTearDown" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.002339" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="0">
                <failure>
                  <message><![CDATA[One or more child tests had errors]]></message>
                </failure>
                <test-case id="0-1027" name="Test" fullname="NUnit.Xml.TestLogger.NetFull.Tests.FailingTearDown.Test" methodname="Test" classname="NUnit.Xml.TestLogger.NetFull.Tests.FailingTearDown" runstate="Runnable" seed="660312617" result="Failed" label="Error" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.002155" asserts="0">
                  <failure>
                    <message><![CDATA[TearDown : System.InvalidOperationException : Operation is not valid due to the current state of the object.]]></message>
                    <stack-trace><![CDATA[--TearDown
   at NUnit.Xml.TestLogger.NetFull.Tests.FailingTearDown.TearDown() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 137]]></stack-trace>
                  </failure>
                </test-case>
              </test-suite>
              <test-suite type="TestFixture" id="0-1024" name="FailingTestSetup" fullname="NUnit.Xml.TestLogger.NetFull.Tests.FailingTestSetup" classname="NUnit.Xml.TestLogger.NetFull.Tests.FailingTestSetup" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.002708" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="0">
                <failure>
                  <message><![CDATA[One or more child tests had errors]]></message>
                </failure>
                <test-case id="0-1025" name="Test" fullname="NUnit.Xml.TestLogger.NetFull.Tests.FailingTestSetup.Test" methodname="Test" classname="NUnit.Xml.TestLogger.NetFull.Tests.FailingTestSetup" runstate="Runnable" seed="1664478297" result="Failed" label="Error" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.002512" asserts="0">
                  <failure>
                    <message><![CDATA[System.InvalidOperationException : Operation is not valid due to the current state of the object.]]></message>
                    <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.FailingTestSetup.SetUp() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 122]]></stack-trace>
                  </failure>
                </test-case>
              </test-suite>
              <test-suite type="ParameterizedFixture" id="0-1034" name="ParametrizedFixture" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture" runstate="Runnable" testcasecount="2" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.054878" total="2" passed="2" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
                <test-suite type="TestFixture" id="0-1032" name="ParametrizedFixture(&quot;Answer&quot;,42)" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture(&quot;Answer&quot;,42)" classname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture" runstate="Runnable" testcasecount="1" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000246" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
                  <test-case id="0-1033" name="Test" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture(&quot;Answer&quot;,42).Test" methodname="Test" classname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture" runstate="Runnable" seed="1806685083" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000098" asserts="0" />
                </test-suite>
                <test-suite type="TestFixture" id="0-1030" name="ParametrizedFixture(&quot;Question&quot;,1)" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture(&quot;Question&quot;,1)" classname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture" runstate="Runnable" testcasecount="1" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000103" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
                  <test-case id="0-1031" name="Test" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture(&quot;Question&quot;,1).Test" methodname="Test" classname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedFixture" runstate="Runnable" seed="169220078" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000051" asserts="0" />
                </test-suite>
              </test-suite>
              <test-suite type="TestFixture" id="0-1035" name="ParametrizedTestCases" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" classname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.057409" total="4" passed="2" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="6">
                <failure>
                  <message><![CDATA[One or more child tests had errors]]></message>
                </failure>
                <test-suite type="ParameterizedMethod" id="0-1040" name="TestData" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData" classname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.057213" total="4" passed="2" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="6">
                  <failure>
                    <message><![CDATA[One or more child tests had errors]]></message>
                  </failure>
                  <test-case id="0-1036" name="TestData(1,&quot;A&quot;)" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData(1,&quot;A&quot;)" methodname="TestData" classname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" runstate="Runnable" seed="550487056" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.022169" asserts="2" />
                  <test-case id="0-1037" name="TestData(1,&quot;B&quot;)" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData(1,&quot;B&quot;)" methodname="TestData" classname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" runstate="Runnable" seed="310261845" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000092" asserts="2" />
                  <test-case id="0-1038" name="TestData(2,&quot;A&quot;)" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData(2,&quot;A&quot;)" methodname="TestData" classname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" runstate="Runnable" seed="509128129" result="Failed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.033679" asserts="1">
                    <failure>
                      <message><![CDATA[  failing for second case
  Expected: not equal to 2
  But was:  2
]]></message>
                      <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData(Int32 x, String s) in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 187
]]></stack-trace>
                    </failure>
                    <assertions>
                      <assertion result="Failed">
                        <message><![CDATA[  failing for second case
  Expected: not equal to 2
  But was:  2
]]></message>
                        <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData(Int32 x, String s) in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 187
]]></stack-trace>
                      </assertion>
                    </assertions>
                  </test-case>
                  <test-case id="0-1039" name="TestData(2,&quot;B&quot;)" fullname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData(2,&quot;B&quot;)" methodname="TestData" classname="NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases" runstate="Runnable" seed="1739857508" result="Failed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000749" asserts="1">
                    <failure>
                      <message><![CDATA[  failing for second case
  Expected: not equal to 2
  But was:  2
]]></message>
                      <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData(Int32 x, String s) in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 187
]]></stack-trace>
                    </failure>
                    <assertions>
                      <assertion result="Failed">
                        <message><![CDATA[  failing for second case
  Expected: not equal to 2
  But was:  2
]]></message>
                        <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.ParametrizedTestCases.TestData(Int32 x, String s) in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 187
]]></stack-trace>
                      </assertion>
                    </assertions>
                  </test-case>
                </test-suite>
              </test-suite>
              <test-suite type="TestFixture" id="0-1019" name="SuccessAndInconclusiveFixture" fullname="NUnit.Xml.TestLogger.NetFull.Tests.SuccessAndInconclusiveFixture" classname="NUnit.Xml.TestLogger.NetFull.Tests.SuccessAndInconclusiveFixture" runstate="Runnable" testcasecount="2" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.001768" total="2" passed="1" failed="0" warnings="0" inconclusive="1" skipped="0" asserts="0">
                <test-case id="0-1021" name="InconclusiveTest" fullname="NUnit.Xml.TestLogger.NetFull.Tests.SuccessAndInconclusiveFixture.InconclusiveTest" methodname="InconclusiveTest" classname="NUnit.Xml.TestLogger.NetFull.Tests.SuccessAndInconclusiveFixture" runstate="Runnable" seed="1307023260" result="Inconclusive" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.001422" asserts="0" />
                <test-case id="0-1020" name="SuccessTest" fullname="NUnit.Xml.TestLogger.NetFull.Tests.SuccessAndInconclusiveFixture.SuccessTest" methodname="SuccessTest" classname="NUnit.Xml.TestLogger.NetFull.Tests.SuccessAndInconclusiveFixture" runstate="Runnable" seed="1545433339" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000116" asserts="0" />
              </test-suite>
              <test-suite type="TestFixture" id="0-1017" name="SuccessFixture" fullname="NUnit.Xml.TestLogger.NetFull.Tests.SuccessFixture" classname="NUnit.Xml.TestLogger.NetFull.Tests.SuccessFixture" runstate="Runnable" testcasecount="1" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000170" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
                <test-case id="0-1018" name="SuccessTest" fullname="NUnit.Xml.TestLogger.NetFull.Tests.SuccessFixture.SuccessTest" methodname="SuccessTest" classname="NUnit.Xml.TestLogger.NetFull.Tests.SuccessFixture" runstate="Runnable" seed="1603427838" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000069" asserts="0" />
              </test-suite>
              <test-suite type="TestFixture" id="0-1005" name="UnitTest1" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.421586" total="4" passed="1" failed="1" warnings="0" inconclusive="1" skipped="1" asserts="1">
                <failure>
                  <message><![CDATA[One or more child tests had errors]]></message>
                </failure>
                <test-case id="0-1007" name="FailTest11" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1.FailTest11" methodname="FailTest11" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" runstate="Runnable" seed="1404795297" result="Failed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.002214" asserts="1">
                  <failure>
                    <message><![CDATA[  Expected: False
  But was:  True
]]></message>
                    <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1.FailTest11() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 20
]]></stack-trace>
                  </failure>
                  <assertions>
                    <assertion result="Failed">
                      <message><![CDATA[  Expected: False
  But was:  True
]]></message>
                      <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1.FailTest11() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 20
]]></stack-trace>
                    </assertion>
                  </assertions>
                </test-case>
                <test-case id="0-1009" name="Ignored" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1.Ignored" methodname="Ignored" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" runstate="Ignored" seed="930858156" result="Skipped" label="Ignored" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.001297" asserts="0">
                  <properties>
                    <property name="_SKIPREASON" value="ignore reason" />
                  </properties>
                  <reason>
                    <message><![CDATA[ignore reason]]></message>
                  </reason>
                </test-case>
                <test-case id="0-1008" name="Inconclusive" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1.Inconclusive" methodname="Inconclusive" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" runstate="Runnable" seed="854458153" result="Inconclusive" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.003917" asserts="0">
                  <reason>
                    <message><![CDATA[test inconclusive]]></message>
                  </reason>
                </test-case>
                <test-case id="0-1006" name="PassTest11" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1.PassTest11" methodname="PassTest11" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest1" runstate="Runnable" seed="909207103" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.412799" asserts="0">
                  <properties>
                    <property name="Description" value="Passing test description" />
                  </properties>
                </test-case>
              </test-suite>
              <test-suite type="TestFixture" id="0-1010" name="UnitTest2" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" runstate="Runnable" testcasecount="6" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.009923" total="5" passed="1" failed="1" warnings="1" inconclusive="1" skipped="2" asserts="2">
                <failure>
                  <message><![CDATA[One or more child tests had errors]]></message>
                </failure>
                <test-case id="0-1016" name="ExplicitTest" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2.ExplicitTest" methodname="ExplicitTest" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" runstate="Explicit" seed="1898571373" result="Skipped" label="Explicit" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000072" asserts="0" />
                <test-case id="0-1012" name="FailTest22" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2.FailTest22" methodname="FailTest22" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" runstate="Runnable" seed="1765035028" result="Failed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.001065" asserts="1">
                  <properties>
                    <property name="Category" value="failing category" />
                  </properties>
                  <failure>
                    <message><![CDATA[  Expected: False
  But was:  True
]]></message>
                    <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2.FailTest22() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 49
]]></stack-trace>
                  </failure>
                  <assertions>
                    <assertion result="Failed">
                      <message><![CDATA[  Expected: False
  But was:  True
]]></message>
                      <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2.FailTest22() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 49
]]></stack-trace>
                    </assertion>
                  </assertions>
                </test-case>
                <test-case id="0-1014" name="IgnoredTest" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2.IgnoredTest" methodname="IgnoredTest" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" runstate="Ignored" seed="1896120091" result="Skipped" label="Ignored" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000009" asserts="0">
                  <properties>
                    <property name="_SKIPREASON" value="ignore reason" />
                  </properties>
                  <reason>
                    <message><![CDATA[ignore reason]]></message>
                  </reason>
                </test-case>
                <test-case id="0-1013" name="Inconclusive" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2.Inconclusive" methodname="Inconclusive" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" runstate="Runnable" seed="26699375" result="Inconclusive" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000803" asserts="0" />
                <test-case id="0-1011" name="PassTest21" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2.PassTest21" methodname="PassTest21" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" runstate="Runnable" seed="1824180650" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000492" asserts="1">
                  <properties>
                    <property name="Category" value="passing category" />
                  </properties>
                </test-case>
                <test-case id="0-1015" name="WarningTest" fullname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2.WarningTest" methodname="WarningTest" classname="NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2" runstate="Runnable" seed="466930055" result="Warning" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.005115" asserts="0">
                  <reason>
                    <message><![CDATA[Warning]]></message>
                  </reason>
                  <assertions>
                    <assertion result="Warning">
                      <message><![CDATA[Warning]]></message>
                      <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests.UnitTest2.WarningTest() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest1.cs:line 67
]]></stack-trace>
                    </assertion>
                  </assertions>
                </test-case>
              </test-suite>
            </test-suite>
            <test-suite type="TestSuite" id="0-1046" name="Tests2" fullname="NUnit.Xml.TestLogger.NetFull.Tests2" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:29Z" duration="0.967483" total="4" passed="1" failed="1" warnings="0" inconclusive="1" skipped="1" asserts="1">
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-suite type="TestFixture" id="0-1000" name="UnitTest21" fullname="NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21" classname="NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:29Z" duration="0.419515" total="4" passed="1" failed="1" warnings="0" inconclusive="1" skipped="1" asserts="1">
                <failure>
                  <message><![CDATA[One or more child tests had errors]]></message>
                </failure>
                <test-case id="0-1002" name="FailTest11" fullname="NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21.FailTest11" methodname="FailTest11" classname="NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21" runstate="Runnable" seed="1666816180" result="Failed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.001277" asserts="1">
                  <failure>
                    <message><![CDATA[  Expected: False
  But was:  True
]]></message>
                    <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21.FailTest11() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest2.cs:line 20
]]></stack-trace>
                  </failure>
                  <assertions>
                    <assertion result="Failed">
                      <message><![CDATA[  Expected: False
  But was:  True
]]></message>
                      <stack-trace><![CDATA[   at NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21.FailTest11() in C:\Users\codit\src\nunit.testlogger\test\assets\NUnit.Xml.TestLogger.NetCore.Tests\UnitTest2.cs:line 20
]]></stack-trace>
                    </assertion>
                  </assertions>
                </test-case>
                <test-case id="0-1004" name="Ignored" fullname="NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21.Ignored" methodname="Ignored" classname="NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21" runstate="Ignored" seed="1172242326" result="Skipped" label="Ignored" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.000049" asserts="0">
                  <properties>
                    <property name="_SKIPREASON" value="ignore reason" />
                  </properties>
                  <reason>
                    <message><![CDATA[ignore reason]]></message>
                  </reason>
                </test-case>
                <test-case id="0-1003" name="Inconclusive" fullname="NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21.Inconclusive" methodname="Inconclusive" classname="NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21" runstate="Runnable" seed="1362207237" result="Inconclusive" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:28Z" duration="0.001046" asserts="0">
                  <reason>
                    <message><![CDATA[test inconclusive]]></message>
                  </reason>
                </test-case>
                <test-case id="0-1001" name="PassTest11" fullname="NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21.PassTest11" methodname="PassTest11" classname="NUnit.Xml.TestLogger.NetFull.Tests2.UnitTest21" runstate="Runnable" seed="207668066" result="Passed" start-time="2018-10-30 01:06:28Z" end-time="2018-10-30 01:06:29Z" duration="0.416111" asserts="0">
                  <properties>
                    <property name="Description" value="Passing test description" />
                  </properties>
                </test-case>
              </test-suite>
            </test-suite>
          </test-suite>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>
